service: sls-squigglecon-totally-dined


frameworkVersion: '3'

provider:
  name: aws
  runtime: dotnet6
  profile: sandbox
  region: eu-west-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:*
      Resource: !GetAtt RestaurantTable.Arn

package:
  artifact: bin/Release/net6.0/deploy-package.zip

functions:
  createRestaurant:
    handler: TotallyDinedBackend.Lambda::Lambda.Handler::createRestaurant
    events:
      - http:
          path: restaurant
          method: post
  createReview:
    handler: TotallyDinedBackend.Lambda::Lambda.Handler::createReview
    events:
      - http:
          path: review
          method: post
  getRestaurants:
    handler: TotallyDinedBackend.Lambda::Lambda.Handler::getRestaurants
    events:
      - http:
          path: restaurant
          method: get

resources:
  Resources:
    RestaurantTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Restaurant-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: PartitionKey
            AttributeType: S
          - AttributeName: SortKey
            AttributeType: S
        KeySchema:
          - AttributeName: PartitionKey
            KeyType: HASH
          - AttributeName: SortKey
            KeyType: RANGE
